services:
    AppBundle\DataFixtures\ORM\DataUserFixtures:
        tags: [doctrine.fixture.orm]

    AppBundle\DataFixtures\ORM\DataGameFixtures:
        tags: [doctrine.fixture.orm]

    AppBundle\DataFixtures\ORM\DataEditionFixtures:
        tags: [doctrine.fixture.orm]

    AppBundle\DataFixtures\ORM\DataPlayerFixtures:
        tags: [doctrine.fixture.orm]