services:
    app.form.type.user.authentication.authenticate:
        class: AppBundle\Form\Type\User\Authentication\AuthenticateType
        public: true
        arguments: ['@router']
        tags:
            - { name: form.type, alias: app_form_type_user_authentication_authenticate }

    app.form.type.survey_response.creation.create:
        class: AppBundle\Form\Type\SurveyResponse\Creation\SurveyResponseCreate
        public: true
        arguments: ['@router']
        tags:
            - { name: form.type, alias: app_form_type_survey_response_creation_create }