services:
    app.listener.user:
        class: AppBundle\Service\Listener\UserListener
        parent: app.util.abstract_container_aware
        tags:
            - { name: doctrine.orm.entity_listener, entity: AppBundle\Entity\User, event: prePersist }
            - { name: doctrine.orm.entity_listener, entity: AppBundle\Entity\User, event: preUpdate }

    app.listener.survey_response:
        class: AppBundle\Service\Listener\SurveyResponseListener
        parent: app.util.abstract_container_aware
        tags:
            - { name: doctrine.orm.entity_listener, entity: AppBundle\Entity\SurveyResponse, event: prePersist }