<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Edition;
use AppBundle\Entity\Player;
use Doctrine\ORM\EntityRepository;

/**
 * EditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditionRepository extends EntityRepository
{
    public function findAll()
    {
        /** @var Edition[] $editions */
        $editions = $this->findBy(array(), array('date' => 'DESC'));

        return $editions;
    }

    /**
     * @param $a Player
     * @param $b Player
     * @return int
     */
    private static function cmp($a, $b)
    {
        return (($a->getPoint() < $b->getPoint()) ? -1 : (($a === $b) ? 0 : 1));
    }
}
