AppBundle\Entity\SurveyResponse:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\SurveyResponseRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
        lastName:
            type: string
            length: 255
    manyToMany:
        games:
            targetEntity: AppBundle\Entity\Game
            inversedBy: surveyResponses
            joinTable:
                name: surveyresponse_game
                joinColumns:
                    survey_response_id:
                        referencedColumnName: id
                        nullable: false
                        unique: false
            inversedJoinColumns:
                game_id:
                    referenceColumnName: id
            cascade: [ persist ]
    lifecycleCallbacks: {  }
